# -*- coding: utf-8 -*-
"""Khelo gram LandingPage Chatbot1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ytahN2TAoCrqi18-57oSH8McXOV1bem
"""

import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

df = pd.read_csv("/content/Khelo gram Landing Page Chatbot - Sheet1 (1).csv")

df.dropna(inplace=True)

vectorizer = TfidfVectorizer()
vectorizer.fit(np.concatenate((df.Question, df.Answer)))

Question_vectors = vectorizer.transform(df.Question)

print("PlayCo Bot: Hi! My name is PlayCo, I'm your virtual assistant. How can I help you?")

question_count = 0
threshold = 0.3

while True:
    input_question = input("User: ")

    input_question_vector = vectorizer.transform([input_question])
    similarities = cosine_similarity(input_question_vector, Question_vectors)

    most_similar_index = np.argmax(similarities, axis=1)[0]
    max_similarity = similarities[0][most_similar_index]

    if max_similarity < threshold:
        print("PlayCo Bot: Sorry. I am not able to give answer of this question.")
    else:
        print("PlayCo Bot: " + df.Answer.iloc[most_similar_index])

    question_count += 1

    if question_count % 3 == 0:
        follow_up = input(
            "PlayCo Bot: Do you want to ask more queries? (Yes/No): "
        ).strip().lower()

        if follow_up == "yes":
            print("PlayCo Bot: How can I assist you?")
            continue
        else:
            print(
                "PlayCo Bot: Thank you for visit. Anytime you feel any query please use me. I am always here for help you."
            )
            break

